[package]
name = "ollamars"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"

bytes = "1.11.0"
futures-util = "0.3.31"
reqwest = "0.12.28"
serde = "1.0.228"
serde_json = "1.0.147"
tokio = { version = "1.48.0", features = ["full", "bytes"] }
tokio-stream = "0.1.17"
